# --- Autostart ---

exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id clipmenud
exec --no-startup-id dunst
exec --no-startup-id xss-lock --transfer-sleep-lock -- ~/.config/i3/scripts/lock.sh --nofork
exec --no-startup-id nm-applet
